// Generated by CoffeeScript 1.3.1
(function() {
  var Connections, connections;

  Connections = require('./connections-server').connections;

  connections = new Connections();

  connections.start();

}).call(this);
